server:
  #  项目端口配置
  port: 8083
  #  项目资源路径配置
  servlet:
    context-path: /peony

#配置数据源
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/peony?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=CTT
    username: root
    password:
    type: com.alibaba.druid.pool.DruidDataSource

#  配置nacos
  application:
#    服务名称
    name: server-peony
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  #  配置文件传输
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 200MB
      max-request-size: 600MB

#  配置redis缓存
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
#        配置连接池最大连接数（使用负值表示没有限制）
        max-active: 8
#        配置连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
#        配置连接池中的最大空闲连接
        max-idle: 8
#        配置连接池中的最小空闲连接
        min-idle: 0
#    配置连接超时时间（毫秒）
    timeout: 300

#配置feign
feign:
  hystrix:
    enabled: true

#结合hystrix dashboard控制面板时，通过HTTP实现一个actuator端点，它需要被启用并公开，默认是只公开heath和info两个端点
management:
  endpoints:
    web:
      exposure:
        include: "*"

#配置ribbon，这里可以只配置ribbon的超时时间，不需要下面的hystrix的超时时间。
#因为ribbon的配置是要大于hystrix的，feign的底层是ribbon的封装的，所以直接配置ribbon
ribbon:
#  处理请求的超时时间 默认5秒
  ReadTimeout: 5000
#  连接建立的超时时长 默认5秒
  ConnectTimeout: 5000

#配置hystrix
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
#            feign整合hystrix，光设置Hystrix超时没用的要配合ribbon超时
            timeoutInMilliseconds: 5000
      circuitBreaker:
#        默认20，熔断的阈值，如果服务报错满足3次，熔断器就会打开，就算order之后请求正确的数据也不行
        requestVolumeThreshold: 3
#        默认5S ， 等5S之后熔断器会处于半开状态，然后下一次请求的正确和错误讲决定熔断器是否真的关闭和是否继续打开
        sleepWindowInMilliseconds: 5000

#配置mybatis-plus
mybatis-plus:
#  mapper扫描包
  mapper-locations: classpath:mapper/*.xml
#  自动扫描pojo包
  type-aliases-package: com.renovation.peony.module.**.entity
  configuration:
#    驼峰转下划线
    map-underscore-to-camel-case: true
  global-config:
    db-config:
#      主键类型
      id-type: auto

#配置日志
logging:
  config: classpath:log4j2-spring.xml