server:
  #  项目端口配置
  port: 8081
  #  项目资源路径配置
  servlet:
    context-path: /rose

#配置数据源
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/rose?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=CTT
    username: root
    password:
    type: com.alibaba.druid.pool.DruidDataSource

#  配置nacos
  application:
    name: server-rose
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  #  配置文件传输
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 200MB
      max-request-size: 600MB

#  配置redis缓存
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
#        配置连接池最大连接数（使用负值表示没有限制）
        max-active: 8
#        配置连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
#        配置连接池中的最大空闲连接
        max-idle: 8
#        配置连接池中的最小空闲连接
        min-idle: 0
#    配置连接超时时间（毫秒）
    timeout: 300

#配置mybatis-plus
mybatis-plus:
#  mapper扫描包
  mapper-locations: classpath:mapper/*.xml
#  自动扫描pojo包
  type-aliases-package: com.renovation.rose.module.**.entity
  configuration:
#    驼峰转下划线
    map-underscore-to-camel-case: true
  global-config:
    db-config:
#      主键类型
      id-type: auto

#配置日志
logging:
  config: classpath:log4j2-spring.xml